let btn = document.querySelector("#btn")

btn.onclick = () => {
    console.log("hello user");
}
btn.onmouseover = () => {
    console.log("this is btn2");
}


//         Event Listners -> modern/efficient way of event handling
//          this is widely used because it can handle events better than the simple event handler

// node.addEventListner("event" , (function which hold tasks that happening after event) => {    })
btn.addEventListener("click" , () => {
    alert("this is generated by the event listner")
})



//Dark-Mode / Light-Mode
let mode = document.querySelector( "#mode" )
let body = document.querySelector( "body" )
let currentMode = "light" ;


mode.addEventListener("click" , () => {
    if(currentMode=="light"){
        // console.log("dark")
        currentMode="dark"
        body.classList.add("dark")
        body.classList.remove("light")
        mode.innerHTML="Light Mode"
    }else{
        // console.log("light")
        currentMode="light"
        body.classList.add("light")
        body.classList.remove("dark")
        mode.innerHTML="Dark Mode"
    }
})
mode.style.backgroundColor="skyblue"
mode.style.padding="10px 20px"
mode.style.borderRadius="5px"
mode.style.border="1px solid black"





// // Event Objects -> it is a special type of object in javascript that has information about the event
// btn.ondblclick = (evt) => {                         // evt -> Event object
//     console.log("this is btn2 double clicked");
// }